//go:cgo_ldflag "/home/scott/Downloads/IBJts/source/cppclient/client/libTwsSocketClient.so"
// Code generated by cmd/cgo; DO NOT EDIT.

package ibapi

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_ClientSock = _Ctype_struct_ClientSock

type _Ctype_Contract = _Ctype_struct_Contract

type _Ctype_OrderId = _Ctype_long

type _Ctype_char int8

type _Ctype_int int32

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_struct_ClientSock struct{}

type _Ctype_struct_Contract struct{}

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgo_runtime_cgocallback runtime.cgocallback
func _cgo_runtime_cgocallback(unsafe.Pointer, unsafe.Pointer, uintptr, uintptr)

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, ...interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})


func _Cfunc_CString(s string) *_Ctype_char {
	p := _cgo_cmalloc(uint64(len(s)+1))
	pp := (*[1<<30]byte)(p)
	copy(pp[:], s)
	pp[len(s)] = 0
	return (*_Ctype_char)(p)
}

//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_contract_currency
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_contract_currency _cgo_45b1e13b81bf_Cfunc_contract_currency
var __cgofn__cgo_45b1e13b81bf_Cfunc_contract_currency byte
var _cgo_45b1e13b81bf_Cfunc_contract_currency = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_contract_currency)

//go:cgo_unsafe_args
func _Cfunc_contract_currency(p0 *_Ctype_struct_Contract) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_contract_currency, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_contract_exchange
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_contract_exchange _cgo_45b1e13b81bf_Cfunc_contract_exchange
var __cgofn__cgo_45b1e13b81bf_Cfunc_contract_exchange byte
var _cgo_45b1e13b81bf_Cfunc_contract_exchange = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_contract_exchange)

//go:cgo_unsafe_args
func _Cfunc_contract_exchange(p0 *_Ctype_struct_Contract) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_contract_exchange, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_contract_month
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_contract_month _cgo_45b1e13b81bf_Cfunc_contract_month
var __cgofn__cgo_45b1e13b81bf_Cfunc_contract_month byte
var _cgo_45b1e13b81bf_Cfunc_contract_month = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_contract_month)

//go:cgo_unsafe_args
func _Cfunc_contract_month(p0 *_Ctype_struct_Contract) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_contract_month, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_contract_sec_type
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_contract_sec_type _cgo_45b1e13b81bf_Cfunc_contract_sec_type
var __cgofn__cgo_45b1e13b81bf_Cfunc_contract_sec_type byte
var _cgo_45b1e13b81bf_Cfunc_contract_sec_type = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_contract_sec_type)

//go:cgo_unsafe_args
func _Cfunc_contract_sec_type(p0 *_Ctype_struct_Contract) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_contract_sec_type, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_contract_symbol
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_contract_symbol _cgo_45b1e13b81bf_Cfunc_contract_symbol
var __cgofn__cgo_45b1e13b81bf_Cfunc_contract_symbol byte
var _cgo_45b1e13b81bf_Cfunc_contract_symbol = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_contract_symbol)

//go:cgo_unsafe_args
func _Cfunc_contract_symbol(p0 *_Ctype_struct_Contract) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_contract_symbol, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_delete_client_sock
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_delete_client_sock _cgo_45b1e13b81bf_Cfunc_delete_client_sock
var __cgofn__cgo_45b1e13b81bf_Cfunc_delete_client_sock byte
var _cgo_45b1e13b81bf_Cfunc_delete_client_sock = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_delete_client_sock)

//go:cgo_unsafe_args
func _Cfunc_delete_client_sock(p0 *_Ctype_struct_ClientSock) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_delete_client_sock, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_delete_contract
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_delete_contract _cgo_45b1e13b81bf_Cfunc_delete_contract
var __cgofn__cgo_45b1e13b81bf_Cfunc_delete_contract byte
var _cgo_45b1e13b81bf_Cfunc_delete_contract = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_delete_contract)

//go:cgo_unsafe_args
func _Cfunc_delete_contract(p0 *_Ctype_struct_Contract) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_delete_contract, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_free
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_free _cgo_45b1e13b81bf_Cfunc_free
var __cgofn__cgo_45b1e13b81bf_Cfunc_free byte
var _cgo_45b1e13b81bf_Cfunc_free = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_free)

//go:cgo_unsafe_args
func _Cfunc_free(p0 unsafe.Pointer) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_free, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_new_client_sock
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_new_client_sock _cgo_45b1e13b81bf_Cfunc_new_client_sock
var __cgofn__cgo_45b1e13b81bf_Cfunc_new_client_sock byte
var _cgo_45b1e13b81bf_Cfunc_new_client_sock = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_new_client_sock)

//go:cgo_unsafe_args
func _Cfunc_new_client_sock(p0 _Ctype_long) (r1 *_Ctype_struct_ClientSock) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_new_client_sock, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_new_contract
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_new_contract _cgo_45b1e13b81bf_Cfunc_new_contract
var __cgofn__cgo_45b1e13b81bf_Cfunc_new_contract byte
var _cgo_45b1e13b81bf_Cfunc_new_contract = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_new_contract)

//go:cgo_unsafe_args
func _Cfunc_new_contract(p0 *_Ctype_char, p1 *_Ctype_char, p2 *_Ctype_char, p3 *_Ctype_char, p4 *_Ctype_char) (r1 *_Ctype_struct_Contract) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_new_contract, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_sock_econnect
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_sock_econnect _cgo_45b1e13b81bf_Cfunc_sock_econnect
var __cgofn__cgo_45b1e13b81bf_Cfunc_sock_econnect byte
var _cgo_45b1e13b81bf_Cfunc_sock_econnect = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_sock_econnect)

//go:cgo_unsafe_args
func _Cfunc_sock_econnect(p0 *_Ctype_struct_ClientSock, p1 *_Ctype_char, p2 _Ctype_int, p3 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_sock_econnect, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc_sock_edisconnect
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc_sock_edisconnect _cgo_45b1e13b81bf_Cfunc_sock_edisconnect
var __cgofn__cgo_45b1e13b81bf_Cfunc_sock_edisconnect byte
var _cgo_45b1e13b81bf_Cfunc_sock_edisconnect = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc_sock_edisconnect)

//go:cgo_unsafe_args
func _Cfunc_sock_edisconnect(p0 *_Ctype_struct_ClientSock) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc_sock_edisconnect, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_export_dynamic nextValidIDCallback
//go:linkname _cgoexp_45b1e13b81bf_nextValidIDCallback _cgoexp_45b1e13b81bf_nextValidIDCallback
//go:cgo_export_static _cgoexp_45b1e13b81bf_nextValidIDCallback
//go:nosplit
//go:norace
func _cgoexp_45b1e13b81bf_nextValidIDCallback(a unsafe.Pointer, n int32, ctxt uintptr) {
	fn := _cgoexpwrap_45b1e13b81bf_nextValidIDCallback
	_cgo_runtime_cgocallback(**(**unsafe.Pointer)(unsafe.Pointer(&fn)), a, uintptr(n), ctxt);
}

func _cgoexpwrap_45b1e13b81bf_nextValidIDCallback(p0 _Ctype_long, p1 _Ctype_OrderId) {
	nextValidIDCallback(p0, p1)
}

//go:cgo_import_static _cgo_45b1e13b81bf_Cfunc__Cmalloc
//go:linkname __cgofn__cgo_45b1e13b81bf_Cfunc__Cmalloc _cgo_45b1e13b81bf_Cfunc__Cmalloc
var __cgofn__cgo_45b1e13b81bf_Cfunc__Cmalloc byte
var _cgo_45b1e13b81bf_Cfunc__Cmalloc = unsafe.Pointer(&__cgofn__cgo_45b1e13b81bf_Cfunc__Cmalloc)

//go:linkname runtime_throw runtime.throw
func runtime_throw(string)

//go:cgo_unsafe_args
func _cgo_cmalloc(p0 uint64) (r1 unsafe.Pointer) {
	_cgo_runtime_cgocall(_cgo_45b1e13b81bf_Cfunc__Cmalloc, uintptr(unsafe.Pointer(&p0)))
	if r1 == nil {
		runtime_throw("runtime: C malloc failed")
	}
	return
}
