/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdlib.h>
#include "_cgo_export.h"

extern void crosscall2(void (*fn)(void *, int, __SIZE_TYPE__), void *, int, __SIZE_TYPE__);
extern __SIZE_TYPE__ _cgo_wait_runtime_init_done();
extern void _cgo_release_context(__SIZE_TYPE__);

extern char* _cgo_topofstack(void);
#define CGO_NO_SANITIZE_THREAD
#define _cgo_tsan_acquire()
#define _cgo_tsan_release()


#define _cgo_msan_write(addr, sz)

extern void _cgoexp_15813bb8b485_updateAccountTimeCallback(void *, int, __SIZE_TYPE__);

CGO_NO_SANITIZE_THREAD
void updateAccountTimeCallback(long int p0, char* p1)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		long int p0;
		char* p1;
	} __attribute__((__packed__, __gcc_struct__)) a;
	a.p0 = p0;
	a.p1 = p1;
	_cgo_tsan_release();
	crosscall2(_cgoexp_15813bb8b485_updateAccountTimeCallback, &a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_15813bb8b485_errorCallback(void *, int, __SIZE_TYPE__);

CGO_NO_SANITIZE_THREAD
void errorCallback(long int p0, int p1, int p2, char* p3)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		long int p0;
		int p1;
		int p2;
		char* p3;
	} __attribute__((__packed__, __gcc_struct__)) a;
	a.p0 = p0;
	a.p1 = p1;
	a.p2 = p2;
	a.p3 = p3;
	_cgo_tsan_release();
	crosscall2(_cgoexp_15813bb8b485_errorCallback, &a, 24, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_15813bb8b485_connectionClosedCallback(void *, int, __SIZE_TYPE__);

CGO_NO_SANITIZE_THREAD
void connectionClosedCallback(long int p0)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		long int p0;
	} __attribute__((__packed__, __gcc_struct__)) a;
	a.p0 = p0;
	_cgo_tsan_release();
	crosscall2(_cgoexp_15813bb8b485_connectionClosedCallback, &a, 8, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_15813bb8b485_nextValidIDCallback(void *, int, __SIZE_TYPE__);

CGO_NO_SANITIZE_THREAD
void nextValidIDCallback(long int p0, OrderId p1)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		long int p0;
		OrderId p1;
	} __attribute__((__packed__, __gcc_struct__)) a;
	a.p0 = p0;
	a.p1 = p1;
	_cgo_tsan_release();
	crosscall2(_cgoexp_15813bb8b485_nextValidIDCallback, &a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_15813bb8b485_accountSummaryCallback(void *, int, __SIZE_TYPE__);

CGO_NO_SANITIZE_THREAD
void accountSummaryCallback(long int p0, int p1, char* p2, char* p3, char* p4, char* p5)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		long int p0;
		int p1;
		char __pad0[4];
		char* p2;
		char* p3;
		char* p4;
		char* p5;
	} __attribute__((__packed__, __gcc_struct__)) a;
	a.p0 = p0;
	a.p1 = p1;
	a.p2 = p2;
	a.p3 = p3;
	a.p4 = p4;
	a.p5 = p5;
	_cgo_tsan_release();
	crosscall2(_cgoexp_15813bb8b485_accountSummaryCallback, &a, 48, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
extern void _cgoexp_15813bb8b485_accountSummaryEndCallback(void *, int, __SIZE_TYPE__);

CGO_NO_SANITIZE_THREAD
void accountSummaryEndCallback(long int p0, int p1)
{
	__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
	struct {
		long int p0;
		int p1;
		char __pad0[4];
	} __attribute__((__packed__, __gcc_struct__)) a;
	a.p0 = p0;
	a.p1 = p1;
	_cgo_tsan_release();
	crosscall2(_cgoexp_15813bb8b485_accountSummaryEndCallback, &a, 16, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}

CGO_NO_SANITIZE_THREAD
void _cgo_15813bb8b485_Cfunc__Cmalloc(void *v) {
	struct {
		unsigned long long p0;
		void *r1;
	} __attribute__((__packed__, __gcc_struct__)) *a = v;
	void *ret;
	_cgo_tsan_acquire();
	ret = malloc(a->p0);
	if (ret == 0 && a->p0 == 0) {
		ret = malloc(1);
	}
	a->r1 = ret;
	_cgo_tsan_release();
}
